FROM maven:3.6-jdk-8-slim as build
FROM icr.io/appcafe/websphere-liberty:full-java8-ibmjava-ubi
COPY --chown=1001:0 ./target/*.*ar /config/apps
COPY --chown=1001:0 ./src/main/liberty/config/server.xml /config
COPY --chown=1001:0 ./src/main/liberty/lib/*.* /opt/ibm/wlp/usr/shared/config/lib/global/

