Version: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: daytrader21
  annotations:
    cloudpakName: "IBM WebSphere Hybrid Edition"
    cloudpakId: "6358611af04743f99f42dadcd6e39d52"
    productCloudpakRatio: "4:1"
    productID: "e7daacc46bbe4e2dacd2af49145a4723"
    productName: "IBM WebSphere Application Server"
    productMetric: "VIRTUAL_PROCESSOR_CORE"
    productChargedContainers: "All"
spec:
  replicas: 1
  applicationImage: 'image-registry.openshift-image-registry.svc:5000/daytrader-wlp/daytrader2wlp:latest'
  expose: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  # Environment entries from daytrader2-db2-secret to access DayTrader databases
     envFrom:
        - secretRef:
               name: daytrader2-db2-secret
                 # Set name for Instana service
                   env:
                     - name: INSTANA_SERVICE_NAME
                         value: "Daytrader2WLP-OCP"
  
                         value: "Daytrader2WLP-OCP"
